version: "2.4"

services:
  #  in such context the database will not have enough memory, http://www.teamfoundation.co.za/2018/05/07/docker-linux-and-windows-event-more-3-from-containers-lcow/
  database:
    platform: windows
    container_name: openimis-db
    build:
      context: ../openimis-db_dkr
      args:
        - ACCEPT_EULA=${ACCEPT_EULA}
        - SA_PASSWORD=${DB_PASSWORD}
    environment:
        - ACCEPT_EULA=${ACCEPT_EULA}
        - SA_PASSWORD=${DB_PASSWORD}
    networks:
      - openimis-net
    ## WARNING:
    ## exposing the database port outside the openimis-net network
    ## may lead to security issue (depending on your network topology)
    # ports:
    #  - 1433:1433
  backend:
    platform: linux
    container_name: openimis-backend
    build: ../openimis-be_py
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REMOTE_USER_AUTHENTICATION=True
      - SITE_ROOT=api
    networks:
      - openimis-net
    # WARNING:
    # exposing the backend port outside the openimis-net network
    # may lead to security issue (depending on your network topology)
    ports:
     - 8000:8000
    # OPTION:
    # if you want to ensure the (demo) db is started prior to backend,
    # simply add the following dependency
    depends_on:
      - database
  frontend:
    platform: linux
    container_name: openimis-frontend
    build: ../openimis-fe_js
    command: serve -s build
    networks:
      - openimis-net
    # WARNING:
    # exposing the frontend port outside the openimis-net network
    # may lead to security issue (depending on your network topology)
    ports:
     - 5000:5000
  gateway:
    platform: linux
    container_name: openimis-gateway
    build:
      context: ../openimis-gateway_dkr
    networks:
      - openimis-net
    ports:
      - 80:80
    # WARNING:
    # demo configuration doesn't setup the SSL (certficate,...)
    # this is a security issue that has to be fixed before exposing the gateway to the internet!
    # - 443:443
    depends_on:
      - backend
      - frontend
  legacy_frontend:
    platform: windows
    container_name: openimis-webapp
    build:
      context: ./VB_app
      dockerfile: ./Dockerfile
    environment:
      - DB_PASS=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
    ports:
      - "8080:80"
    networks:
      - openimis-net
networks:
  openimis-net:
